### ISSUE TITLE
First entry on fresh installation causes system to crash and data loss

### ISSUE THREAD

**Issue by brendanwallace** [xuhanz/DailyDose#24]
Subsequent entries work fine.

I was able to reproduce this by wiping files on the emulated device and reinstalling Daily Dose.  Seems to happen every time.

After clicking 'SUBMIT' on the very first entry, the system crashes and the log entry is not saved (nothing is visible in the log, and after creating more entries this first entry never appears - so it seems to be lost).

Probably an issue with instantiating the file.  Maybe even a race condition, if file creation is being dispatched asynchronously?

**Comment by HunterF98** [comment]
Thank you for bringing this to our attention! Fixed in a separate branch, and making a pull request now

**Comment by brendanwallace** [comment]
Typically don't close an issue until the resolution is merged into master.

**Comment by HunterF98** [comment]
Thank you for the clarification, it is now!
