### ISSUE TITLE
User Manual Issues

### ISSUE THREAD

**Issue by Oyestrone** [xuhanz/DailyDose#50]
User thinks we should have more detailed explanations of the functionalities of our app.

**Comment by xuhanz** [comment]
Include a URL for users to download Android Studio.
Help users find AVD manager as users might use Android Studio for the first time.
Highlight the version of emulator and API (Application will fail if those don’t match)

**Comment by HunterF98** [comment]
Include that the App requires Android 4.2 to run in here and README.md

**Comment by Oyestrone** [comment]
All feedback incorporated.
