### ISSUE TITLE
Developer Guideline Issues

### ISSUE THREAD

**Issue by Oyestrone** [xuhanz/DailyDose#52]
Add more instructions regarding the format of newly added tests so they can fit in with existing tests.

**Comment by Oyestrone** [comment]
Include actual coding guidelines in case someone wants to contribute and add code.

**Comment by mjg1124** [comment]
Improve clarity of repository structure - I believe I already have that handled in a local branch I'm working in.

**Comment by HunterF98** [comment]
Put "How to Report Issues" section in here as well.

**Comment by HunterF98** [comment]
Add info about the CI system and how it is triggered

**Comment by Oyestrone** [comment]
Fixed everything.
